print ("Batir huevos")
print ("Agregar sal y otros condimentos al batido")
print ("Poner aceite en la sarten")
print ("Poner sarten en el fuego")
print ("Sumergir carne en el batido")
print ("Untar carne con pan rallado")
print ("Sumergir milanesa en aceite caliente")
print ("Esperar que se cocine")
print ("Quitarla del aceite")
